Kitsunet:
  ImageManipulation:
    ImageBlob:
      # Maps classnames of \Kitsunet\ImageManipulation\ImageBlob\Manipulation\Description\ManipulationDescriptionInterface implementations
      # to classnames of \Kitsunet\ImageManipulation\ImageBlob\Manipulation\ImageManipulationInterface implementations
      #
      typeBasedManipulationMapping:
        __fallback: '\Kitsunet\ImageManipulation\ImageBlob\Manipulation\PassthroughImageManipulation'
        crop: '\Kitsunet\ImageManipulation\Imagine\CropManipulation'
        resize: '\Kitsunet\ImageManipulation\Imagine\ResizeManipulation'
        grayscale: '\Kitsunet\ImageManipulation\Imagine\GrayscaleManipulation'
        passthrough: '\Kitsunet\ImageManipulation\ImageBlob\Manipulation\PassthroughImageManipulation'
        rotate: '\Kitsunet\ImageManipulation\Imagine\RotateManipulation'
      preDescriptions: []
      postDescriptions:
#        rotate:
#          class: '\Kitsunet\ImageManipulation\ImageBlob\Manipulation\Description\RotateDescription'
#          arguments:
#            - 180
        grayscale:
          class: '\Kitsunet\ImageManipulation\ImageBlob\Manipulation\Description\GenericDescription'
          arguments:
            - 'grayscale'
            - []

    Imagine:
      imageOptions:
        quality: 90
        convertCMYKToRGB: true
        resizeFilter: '%\Imagine\Image\ImageInterface::FILTER_UNDEFINED%'
